import LiuWang.Proof.Interfaces.Main
import MathlibNt.AnalyticNumberTheory.DirichletL.DirichletLQuadraticPolyaVinogradov
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.NumberTheory.NumberField.DedekindZeta

/-!
# The quadratic field generated by an odd real primitive character

The generator is the actual Gauss sum, not an independently chosen square root.
The conductor--discriminant identity and the Dedekind zeta factorization are
not asserted here.
-/

set_option autoImplicit false

noncomputable section

namespace LiuWang.Proof.EffectiveLValue

open Polynomial

abbrev OddRealPrimitiveCharacter (r : ℕ) :=
  {χ : Interfaces.Character r // χ.IsPrimitive ∧ χ ^ 2 = 1 ∧ χ.Odd}

variable {r : ℕ}

theorem character_sq_eq_one_iff_real (χ : Interfaces.Character r) :
    χ ^ 2 = 1 ↔ ∀ a : ZMod r, (χ a).im = 0 := by
  constructor
  · intro h a
    rcases MulChar.isQuadratic_iff_sq_eq_one.mpr h a with h | h | h <;> simp [h]
  · intro h
    have hstar : star χ = χ := by
      ext a
      change star (χ a) = χ a
      exact Complex.conj_eq_iff_im.mpr (h a)
    rw [MulChar.star_eq_inv] at hstar
    calc
      χ ^ 2 = χ⁻¹ * χ := by rw [hstar, pow_two]
      _ = 1 := inv_mul_cancel χ

variable [NeZero r]

def characterGaussSum (χ : Interfaces.Character r) : ℂ :=
  gaussSum χ ZMod.stdAddChar

theorem characterGaussSum_conj (χ : Interfaces.Character r) (hχ : χ ^ 2 = 1) :
    star (characterGaussSum χ) = χ (-1) * characterGaussSum χ := by
  have hinv : χ⁻¹ = χ := (MulChar.isQuadratic_iff_sq_eq_one.mpr hχ).inv
  unfold characterGaussSum
  rw [star_gaussSum_eq, hinv, AddChar.inv_mulShift]
  simpa [hinv] using gaussSum_mulShift_eq χ ZMod.stdAddChar (-1 : (ZMod r)ˣ)

theorem odd_characterGaussSum_sq (χ : OddRealPrimitiveCharacter r) (hr : 1 < r) :
    characterGaussSum χ.1 ^ 2 = -(r : ℂ) := by
  have hstar : star (characterGaussSum χ.1) = -characterGaussSum χ.1 := by
    rw [characterGaussSum_conj χ.1 χ.2.2.1, χ.2.2.2, neg_one_mul]
  have hn : Complex.normSq (characterGaussSum χ.1) = (r : ℝ) := by
    rw [← Complex.sq_norm, characterGaussSum, χ.2.1.norm_gaussSum_stdAddChar hr,
      Real.sq_sqrt (Nat.cast_nonneg r)]
  have hc := congrArg Complex.ofReal hn
  rw [Complex.normSq_eq_conj_mul_self] at hc
  change star (characterGaussSum χ.1) * characterGaussSum χ.1 = (r : ℂ) at hc
  rw [hstar] at hc
  linear_combination -hc

theorem odd_characterGaussSum_not_rat (χ : OddRealPrimitiveCharacter r) (hr : 1 < r) :
    characterGaussSum χ.1 ∉ (algebraMap ℚ ℂ).range := by
  rintro ⟨a, ha⟩
  have hs := odd_characterGaussSum_sq χ hr
  rw [← ha] at hs
  have hre := congrArg Complex.re hs
  have hrpos : (0 : ℝ) < r := by exact_mod_cast (lt_trans Nat.zero_lt_one hr)
  norm_num [pow_two, Complex.mul_re] at hre
  nlinarith [sq_nonneg (a : ℝ)]

theorem odd_characterGaussSum_integral (χ : OddRealPrimitiveCharacter r) (hr : 1 < r) :
    IsIntegral ℚ (characterGaussSum χ.1) := by
  refine ⟨X ^ 2 + C (r : ℚ), monic_X_pow_add_C _ (by decide), ?_⟩
  simp [odd_characterGaussSum_sq χ hr]

def oddCharacterField (χ : OddRealPrimitiveCharacter r) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ {characterGaussSum χ.1}

def oddCharacterGenerator (χ : OddRealPrimitiveCharacter r) : oddCharacterField χ :=
  ⟨characterGaussSum χ.1, IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)⟩

theorem oddCharacterGenerator_sq (χ : OddRealPrimitiveCharacter r) (hr : 1 < r) :
    oddCharacterGenerator χ ^ 2 = -(r : oddCharacterField χ) := by
  apply Subtype.ext
  exact odd_characterGaussSum_sq χ hr

theorem oddCharacterField_finrank (χ : OddRealPrimitiveCharacter r) (hr : 1 < r) :
    Module.finrank ℚ (oddCharacterField χ) = 2 := by
  have hi := odd_characterGaussSum_integral χ hr
  rw [oddCharacterField, IntermediateField.adjoin.finrank hi]
  apply le_antisymm
  · have hd := Polynomial.natDegree_le_natDegree
      (minpoly.min ℚ (characterGaussSum χ.1)
        (monic_X_pow_add_C (r : ℚ) (by decide : (2 : ℕ) ≠ 0))
        (by simp [odd_characterGaussSum_sq χ hr]))
    simpa only [natDegree_X_pow_add_C] using hd
  · exact (minpoly.two_le_natDegree_iff hi).mpr (odd_characterGaussSum_not_rat χ hr)

instance oddCharacterField_numberField (χ : OddRealPrimitiveCharacter r) [Fact (1 < r)] :
    NumberField (oddCharacterField χ) where
  to_finiteDimensional :=
    IntermediateField.adjoin.finiteDimensional
      (odd_characterGaussSum_integral χ (Fact.out : 1 < r))

instance oddCharacterField_quadratic (χ : OddRealPrimitiveCharacter r) [Fact (1 < r)] :
    Algebra.IsQuadraticExtension ℚ (oddCharacterField χ) :=
  ⟨oddCharacterField_finrank χ Fact.out⟩

theorem oddCharacterField_classNumber_ge_one (χ : OddRealPrimitiveCharacter r)
    [Fact (1 < r)] :
    1 ≤ NumberField.classNumber (oddCharacterField χ) :=
  NumberField.classNumber_pos _

end LiuWang.Proof.EffectiveLValue
