import LiuWang.Proof.FiniteTernaryClosure.Main
import Mathlib.Tactic.NormNum.Prime
/-!
# Complete development regression: every odd integer in [9, 1000]

Generated by the in-scope generate_certificates.py. Each row is untrusted
data; the block proofs use kernel-checkable `norm_num`, and the final theorem
joins every block with checkOddRun_append. No sampling or analytic bound
is used. The repeated-prime case 9 = 3 + 3 + 3 is included.
-/

set_option autoImplicit false

namespace LiuWang.Proof.FiniteTernaryClosure

def certificates00 : List Certificate :=
  [⟨9, 3, 3, 3⟩,
    ⟨11, 3, 3, 5⟩,
    ⟨13, 3, 3, 7⟩,
    ⟨15, 3, 5, 7⟩,
    ⟨17, 3, 3, 11⟩,
    ⟨19, 3, 3, 13⟩,
    ⟨21, 3, 5, 13⟩,
    ⟨23, 3, 3, 17⟩,
    ⟨25, 3, 3, 19⟩,
    ⟨27, 3, 5, 19⟩,
    ⟨29, 3, 3, 23⟩,
    ⟨31, 3, 5, 23⟩,
    ⟨33, 3, 7, 23⟩,
    ⟨35, 3, 3, 29⟩,
    ⟨37, 3, 3, 31⟩,
    ⟨39, 3, 5, 31⟩]

theorem checked00 : checkOddRun 9 40 certificates00 = true := by
  norm_num [checkOddRun, checkCertificate, certificates00]

theorem length00 : certificates00.length = 16 := by decide

def certificates01 : List Certificate :=
  [⟨41, 3, 7, 31⟩,
    ⟨43, 3, 3, 37⟩,
    ⟨45, 3, 5, 37⟩,
    ⟨47, 3, 3, 41⟩,
    ⟨49, 3, 3, 43⟩,
    ⟨51, 3, 5, 43⟩,
    ⟨53, 3, 3, 47⟩,
    ⟨55, 3, 5, 47⟩,
    ⟨57, 3, 7, 47⟩,
    ⟨59, 3, 3, 53⟩,
    ⟨61, 3, 5, 53⟩,
    ⟨63, 3, 7, 53⟩,
    ⟨65, 3, 3, 59⟩,
    ⟨67, 3, 3, 61⟩,
    ⟨69, 3, 5, 61⟩,
    ⟨71, 3, 7, 61⟩]

theorem checked01 : checkOddRun 41 72 certificates01 = true := by
  norm_num [checkOddRun, checkCertificate, certificates01]

theorem length01 : certificates01.length = 16 := by decide

def certificates02 : List Certificate :=
  [⟨73, 3, 3, 67⟩,
    ⟨75, 3, 5, 67⟩,
    ⟨77, 3, 3, 71⟩,
    ⟨79, 3, 3, 73⟩,
    ⟨81, 3, 5, 73⟩,
    ⟨83, 3, 7, 73⟩,
    ⟨85, 3, 3, 79⟩,
    ⟨87, 3, 5, 79⟩,
    ⟨89, 3, 3, 83⟩,
    ⟨91, 3, 5, 83⟩,
    ⟨93, 3, 7, 83⟩,
    ⟨95, 3, 3, 89⟩,
    ⟨97, 3, 5, 89⟩,
    ⟨99, 3, 7, 89⟩,
    ⟨101, 3, 19, 79⟩,
    ⟨103, 3, 3, 97⟩]

theorem checked02 : checkOddRun 73 104 certificates02 = true := by
  norm_num [checkOddRun, checkCertificate, certificates02]

theorem length02 : certificates02.length = 16 := by decide

def certificates03 : List Certificate :=
  [⟨105, 3, 5, 97⟩,
    ⟨107, 3, 3, 101⟩,
    ⟨109, 3, 3, 103⟩,
    ⟨111, 3, 5, 103⟩,
    ⟨113, 3, 3, 107⟩,
    ⟨115, 3, 3, 109⟩,
    ⟨117, 3, 5, 109⟩,
    ⟨119, 3, 3, 113⟩,
    ⟨121, 3, 5, 113⟩,
    ⟨123, 3, 7, 113⟩,
    ⟨125, 3, 13, 109⟩,
    ⟨127, 3, 11, 113⟩,
    ⟨129, 3, 13, 113⟩,
    ⟨131, 3, 19, 109⟩,
    ⟨133, 3, 3, 127⟩,
    ⟨135, 3, 5, 127⟩]

theorem checked03 : checkOddRun 105 136 certificates03 = true := by
  norm_num [checkOddRun, checkCertificate, certificates03]

theorem length03 : certificates03.length = 16 := by decide

def certificates04 : List Certificate :=
  [⟨137, 3, 3, 131⟩,
    ⟨139, 3, 5, 131⟩,
    ⟨141, 3, 7, 131⟩,
    ⟨143, 3, 3, 137⟩,
    ⟨145, 3, 3, 139⟩,
    ⟨147, 3, 5, 139⟩,
    ⟨149, 3, 7, 139⟩,
    ⟨151, 3, 11, 137⟩,
    ⟨153, 3, 11, 139⟩,
    ⟨155, 3, 3, 149⟩,
    ⟨157, 3, 3, 151⟩,
    ⟨159, 3, 5, 151⟩,
    ⟨161, 3, 7, 151⟩,
    ⟨163, 3, 3, 157⟩,
    ⟨165, 3, 5, 157⟩,
    ⟨167, 3, 7, 157⟩]

theorem checked04 : checkOddRun 137 168 certificates04 = true := by
  norm_num [checkOddRun, checkCertificate, certificates04]

theorem length04 : certificates04.length = 16 := by decide

def certificates05 : List Certificate :=
  [⟨169, 3, 3, 163⟩,
    ⟨171, 3, 5, 163⟩,
    ⟨173, 3, 3, 167⟩,
    ⟨175, 3, 5, 167⟩,
    ⟨177, 3, 7, 167⟩,
    ⟨179, 3, 3, 173⟩,
    ⟨181, 3, 5, 173⟩,
    ⟨183, 3, 7, 173⟩,
    ⟨185, 3, 3, 179⟩,
    ⟨187, 3, 3, 181⟩,
    ⟨189, 3, 5, 181⟩,
    ⟨191, 3, 7, 181⟩,
    ⟨193, 3, 11, 179⟩,
    ⟨195, 3, 11, 181⟩,
    ⟨197, 3, 3, 191⟩,
    ⟨199, 3, 3, 193⟩]

theorem checked05 : checkOddRun 169 200 certificates05 = true := by
  norm_num [checkOddRun, checkCertificate, certificates05]

theorem length05 : certificates05.length = 16 := by decide

def certificates06 : List Certificate :=
  [⟨201, 3, 5, 193⟩,
    ⟨203, 3, 3, 197⟩,
    ⟨205, 3, 3, 199⟩,
    ⟨207, 3, 5, 199⟩,
    ⟨209, 3, 7, 199⟩,
    ⟨211, 3, 11, 197⟩,
    ⟨213, 3, 11, 199⟩,
    ⟨215, 3, 13, 199⟩,
    ⟨217, 3, 3, 211⟩,
    ⟨219, 3, 5, 211⟩,
    ⟨221, 3, 7, 211⟩,
    ⟨223, 3, 23, 197⟩,
    ⟨225, 3, 11, 211⟩,
    ⟨227, 3, 13, 211⟩,
    ⟨229, 3, 3, 223⟩,
    ⟨231, 3, 5, 223⟩]

theorem checked06 : checkOddRun 201 232 certificates06 = true := by
  norm_num [checkOddRun, checkCertificate, certificates06]

theorem length06 : certificates06.length = 16 := by decide

def certificates07 : List Certificate :=
  [⟨233, 3, 3, 227⟩,
    ⟨235, 3, 3, 229⟩,
    ⟨237, 3, 5, 229⟩,
    ⟨239, 3, 3, 233⟩,
    ⟨241, 3, 5, 233⟩,
    ⟨243, 3, 7, 233⟩,
    ⟨245, 3, 3, 239⟩,
    ⟨247, 3, 3, 241⟩,
    ⟨249, 3, 5, 241⟩,
    ⟨251, 3, 7, 241⟩,
    ⟨253, 3, 11, 239⟩,
    ⟨255, 3, 11, 241⟩,
    ⟨257, 3, 3, 251⟩,
    ⟨259, 3, 5, 251⟩,
    ⟨261, 3, 7, 251⟩,
    ⟨263, 3, 3, 257⟩]

theorem checked07 : checkOddRun 233 264 certificates07 = true := by
  norm_num [checkOddRun, checkCertificate, certificates07]

theorem length07 : certificates07.length = 16 := by decide

def certificates08 : List Certificate :=
  [⟨265, 3, 5, 257⟩,
    ⟨267, 3, 7, 257⟩,
    ⟨269, 3, 3, 263⟩,
    ⟨271, 3, 5, 263⟩,
    ⟨273, 3, 7, 263⟩,
    ⟨275, 3, 3, 269⟩,
    ⟨277, 3, 3, 271⟩,
    ⟨279, 3, 5, 271⟩,
    ⟨281, 3, 7, 271⟩,
    ⟨283, 3, 3, 277⟩,
    ⟨285, 3, 5, 277⟩,
    ⟨287, 3, 3, 281⟩,
    ⟨289, 3, 3, 283⟩,
    ⟨291, 3, 5, 283⟩,
    ⟨293, 3, 7, 283⟩,
    ⟨295, 3, 11, 281⟩]

theorem checked08 : checkOddRun 265 296 certificates08 = true := by
  norm_num [checkOddRun, checkCertificate, certificates08]

theorem length08 : certificates08.length = 16 := by decide

def certificates09 : List Certificate :=
  [⟨297, 3, 11, 283⟩,
    ⟨299, 3, 3, 293⟩,
    ⟨301, 3, 5, 293⟩,
    ⟨303, 3, 7, 293⟩,
    ⟨305, 3, 19, 283⟩,
    ⟨307, 3, 11, 293⟩,
    ⟨309, 3, 13, 293⟩,
    ⟨311, 3, 31, 277⟩,
    ⟨313, 3, 3, 307⟩,
    ⟨315, 3, 5, 307⟩,
    ⟨317, 3, 3, 311⟩,
    ⟨319, 3, 3, 313⟩,
    ⟨321, 3, 5, 313⟩,
    ⟨323, 3, 3, 317⟩,
    ⟨325, 3, 5, 317⟩,
    ⟨327, 3, 7, 317⟩]

theorem checked09 : checkOddRun 297 328 certificates09 = true := by
  norm_num [checkOddRun, checkCertificate, certificates09]

theorem length09 : certificates09.length = 16 := by decide

def certificates10 : List Certificate :=
  [⟨329, 3, 13, 313⟩,
    ⟨331, 3, 11, 317⟩,
    ⟨333, 3, 13, 317⟩,
    ⟨335, 3, 19, 313⟩,
    ⟨337, 3, 3, 331⟩,
    ⟨339, 3, 5, 331⟩,
    ⟨341, 3, 7, 331⟩,
    ⟨343, 3, 3, 337⟩,
    ⟨345, 3, 5, 337⟩,
    ⟨347, 3, 7, 337⟩,
    ⟨349, 3, 29, 317⟩,
    ⟨351, 3, 11, 337⟩,
    ⟨353, 3, 3, 347⟩,
    ⟨355, 3, 3, 349⟩,
    ⟨357, 3, 5, 349⟩,
    ⟨359, 3, 3, 353⟩]

theorem checked10 : checkOddRun 329 360 certificates10 = true := by
  norm_num [checkOddRun, checkCertificate, certificates10]

theorem length10 : certificates10.length = 16 := by decide

def certificates11 : List Certificate :=
  [⟨361, 3, 5, 353⟩,
    ⟨363, 3, 7, 353⟩,
    ⟨365, 3, 3, 359⟩,
    ⟨367, 3, 5, 359⟩,
    ⟨369, 3, 7, 359⟩,
    ⟨371, 3, 19, 349⟩,
    ⟨373, 3, 3, 367⟩,
    ⟨375, 3, 5, 367⟩,
    ⟨377, 3, 7, 367⟩,
    ⟨379, 3, 3, 373⟩,
    ⟨381, 3, 5, 373⟩,
    ⟨383, 3, 7, 373⟩,
    ⟨385, 3, 3, 379⟩,
    ⟨387, 3, 5, 379⟩,
    ⟨389, 3, 3, 383⟩,
    ⟨391, 3, 5, 383⟩]

theorem checked11 : checkOddRun 361 392 certificates11 = true := by
  norm_num [checkOddRun, checkCertificate, certificates11]

theorem length11 : certificates11.length = 16 := by decide

def certificates12 : List Certificate :=
  [⟨393, 3, 7, 383⟩,
    ⟨395, 3, 3, 389⟩,
    ⟨397, 3, 5, 389⟩,
    ⟨399, 3, 7, 389⟩,
    ⟨401, 3, 19, 379⟩,
    ⟨403, 3, 3, 397⟩,
    ⟨405, 3, 5, 397⟩,
    ⟨407, 3, 3, 401⟩,
    ⟨409, 3, 5, 401⟩,
    ⟨411, 3, 7, 401⟩,
    ⟨413, 3, 13, 397⟩,
    ⟨415, 3, 3, 409⟩,
    ⟨417, 3, 5, 409⟩,
    ⟨419, 3, 7, 409⟩,
    ⟨421, 3, 17, 401⟩,
    ⟨423, 3, 11, 409⟩]

theorem checked12 : checkOddRun 393 424 certificates12 = true := by
  norm_num [checkOddRun, checkCertificate, certificates12]

theorem length12 : certificates12.length = 16 := by decide

def certificates13 : List Certificate :=
  [⟨425, 3, 3, 419⟩,
    ⟨427, 3, 3, 421⟩,
    ⟨429, 3, 5, 421⟩,
    ⟨431, 3, 7, 421⟩,
    ⟨433, 3, 11, 419⟩,
    ⟨435, 3, 11, 421⟩,
    ⟨437, 3, 3, 431⟩,
    ⟨439, 3, 3, 433⟩,
    ⟨441, 3, 5, 433⟩,
    ⟨443, 3, 7, 433⟩,
    ⟨445, 3, 3, 439⟩,
    ⟨447, 3, 5, 439⟩,
    ⟨449, 3, 3, 443⟩,
    ⟨451, 3, 5, 443⟩,
    ⟨453, 3, 7, 443⟩,
    ⟨455, 3, 3, 449⟩]

theorem checked13 : checkOddRun 425 456 certificates13 = true := by
  norm_num [checkOddRun, checkCertificate, certificates13]

theorem length13 : certificates13.length = 16 := by decide

def certificates14 : List Certificate :=
  [⟨457, 3, 5, 449⟩,
    ⟨459, 3, 7, 449⟩,
    ⟨461, 3, 19, 439⟩,
    ⟨463, 3, 3, 457⟩,
    ⟨465, 3, 5, 457⟩,
    ⟨467, 3, 3, 461⟩,
    ⟨469, 3, 3, 463⟩,
    ⟨471, 3, 5, 463⟩,
    ⟨473, 3, 3, 467⟩,
    ⟨475, 3, 5, 467⟩,
    ⟨477, 3, 7, 467⟩,
    ⟨479, 3, 13, 463⟩,
    ⟨481, 3, 11, 467⟩,
    ⟨483, 3, 13, 467⟩,
    ⟨485, 3, 3, 479⟩,
    ⟨487, 3, 5, 479⟩]

theorem checked14 : checkOddRun 457 488 certificates14 = true := by
  norm_num [checkOddRun, checkCertificate, certificates14]

theorem length14 : certificates14.length = 16 := by decide

def certificates15 : List Certificate :=
  [⟨489, 3, 7, 479⟩,
    ⟨491, 3, 31, 457⟩,
    ⟨493, 3, 3, 487⟩,
    ⟨495, 3, 5, 487⟩,
    ⟨497, 3, 3, 491⟩,
    ⟨499, 3, 5, 491⟩,
    ⟨501, 3, 7, 491⟩,
    ⟨503, 3, 13, 487⟩,
    ⟨505, 3, 3, 499⟩,
    ⟨507, 3, 5, 499⟩,
    ⟨509, 3, 3, 503⟩,
    ⟨511, 3, 5, 503⟩,
    ⟨513, 3, 7, 503⟩,
    ⟨515, 3, 3, 509⟩,
    ⟨517, 3, 5, 509⟩,
    ⟨519, 3, 7, 509⟩]

theorem checked15 : checkOddRun 489 520 certificates15 = true := by
  norm_num [checkOddRun, checkCertificate, certificates15]

theorem length15 : certificates15.length = 16 := by decide

def certificates16 : List Certificate :=
  [⟨521, 3, 19, 499⟩,
    ⟨523, 3, 11, 509⟩,
    ⟨525, 3, 13, 509⟩,
    ⟨527, 3, 3, 521⟩,
    ⟨529, 3, 3, 523⟩,
    ⟨531, 3, 5, 523⟩,
    ⟨533, 3, 7, 523⟩,
    ⟨535, 3, 11, 521⟩,
    ⟨537, 3, 11, 523⟩,
    ⟨539, 3, 13, 523⟩,
    ⟨541, 3, 17, 521⟩,
    ⟨543, 3, 17, 523⟩,
    ⟨545, 3, 19, 523⟩,
    ⟨547, 3, 3, 541⟩,
    ⟨549, 3, 5, 541⟩,
    ⟨551, 3, 7, 541⟩]

theorem checked16 : checkOddRun 521 552 certificates16 = true := by
  norm_num [checkOddRun, checkCertificate, certificates16]

theorem length16 : certificates16.length = 16 := by decide

def certificates17 : List Certificate :=
  [⟨553, 3, 3, 547⟩,
    ⟨555, 3, 5, 547⟩,
    ⟨557, 3, 7, 547⟩,
    ⟨559, 3, 47, 509⟩,
    ⟨561, 3, 11, 547⟩,
    ⟨563, 3, 3, 557⟩,
    ⟨565, 3, 5, 557⟩,
    ⟨567, 3, 7, 557⟩,
    ⟨569, 3, 3, 563⟩,
    ⟨571, 3, 5, 563⟩,
    ⟨573, 3, 7, 563⟩,
    ⟨575, 3, 3, 569⟩,
    ⟨577, 3, 3, 571⟩,
    ⟨579, 3, 5, 571⟩,
    ⟨581, 3, 7, 571⟩,
    ⟨583, 3, 3, 577⟩]

theorem checked17 : checkOddRun 553 584 certificates17 = true := by
  norm_num [checkOddRun, checkCertificate, certificates17]

theorem length17 : certificates17.length = 16 := by decide

def certificates18 : List Certificate :=
  [⟨585, 3, 5, 577⟩,
    ⟨587, 3, 7, 577⟩,
    ⟨589, 3, 17, 569⟩,
    ⟨591, 3, 11, 577⟩,
    ⟨593, 3, 3, 587⟩,
    ⟨595, 3, 5, 587⟩,
    ⟨597, 3, 7, 587⟩,
    ⟨599, 3, 3, 593⟩,
    ⟨601, 3, 5, 593⟩,
    ⟨603, 3, 7, 593⟩,
    ⟨605, 3, 3, 599⟩,
    ⟨607, 3, 3, 601⟩,
    ⟨609, 3, 5, 601⟩,
    ⟨611, 3, 7, 601⟩,
    ⟨613, 3, 3, 607⟩,
    ⟨615, 3, 5, 607⟩]

theorem checked18 : checkOddRun 585 616 certificates18 = true := by
  norm_num [checkOddRun, checkCertificate, certificates18]

theorem length18 : certificates18.length = 16 := by decide

def certificates19 : List Certificate :=
  [⟨617, 3, 7, 607⟩,
    ⟨619, 3, 3, 613⟩,
    ⟨621, 3, 5, 613⟩,
    ⟨623, 3, 3, 617⟩,
    ⟨625, 3, 3, 619⟩,
    ⟨627, 3, 5, 619⟩,
    ⟨629, 3, 7, 619⟩,
    ⟨631, 3, 11, 617⟩,
    ⟨633, 3, 11, 619⟩,
    ⟨635, 3, 13, 619⟩,
    ⟨637, 3, 3, 631⟩,
    ⟨639, 3, 5, 631⟩,
    ⟨641, 3, 7, 631⟩,
    ⟨643, 3, 23, 617⟩,
    ⟨645, 3, 11, 631⟩,
    ⟨647, 3, 3, 641⟩]

theorem checked19 : checkOddRun 617 648 certificates19 = true := by
  norm_num [checkOddRun, checkCertificate, certificates19]

theorem length19 : certificates19.length = 16 := by decide

def certificates20 : List Certificate :=
  [⟨649, 3, 3, 643⟩,
    ⟨651, 3, 5, 643⟩,
    ⟨653, 3, 3, 647⟩,
    ⟨655, 3, 5, 647⟩,
    ⟨657, 3, 7, 647⟩,
    ⟨659, 3, 3, 653⟩,
    ⟨661, 3, 5, 653⟩,
    ⟨663, 3, 7, 653⟩,
    ⟨665, 3, 3, 659⟩,
    ⟨667, 3, 3, 661⟩,
    ⟨669, 3, 5, 661⟩,
    ⟨671, 3, 7, 661⟩,
    ⟨673, 3, 11, 659⟩,
    ⟨675, 3, 11, 661⟩,
    ⟨677, 3, 13, 661⟩,
    ⟨679, 3, 3, 673⟩]

theorem checked20 : checkOddRun 649 680 certificates20 = true := by
  norm_num [checkOddRun, checkCertificate, certificates20]

theorem length20 : certificates20.length = 16 := by decide

def certificates21 : List Certificate :=
  [⟨681, 3, 5, 673⟩,
    ⟨683, 3, 3, 677⟩,
    ⟨685, 3, 5, 677⟩,
    ⟨687, 3, 7, 677⟩,
    ⟨689, 3, 3, 683⟩,
    ⟨691, 3, 5, 683⟩,
    ⟨693, 3, 7, 683⟩,
    ⟨695, 3, 19, 673⟩,
    ⟨697, 3, 3, 691⟩,
    ⟨699, 3, 5, 691⟩,
    ⟨701, 3, 7, 691⟩,
    ⟨703, 3, 17, 683⟩,
    ⟨705, 3, 11, 691⟩,
    ⟨707, 3, 3, 701⟩,
    ⟨709, 3, 5, 701⟩,
    ⟨711, 3, 7, 701⟩]

theorem checked21 : checkOddRun 681 712 certificates21 = true := by
  norm_num [checkOddRun, checkCertificate, certificates21]

theorem length21 : certificates21.length = 16 := by decide

def certificates22 : List Certificate :=
  [⟨713, 3, 19, 691⟩,
    ⟨715, 3, 3, 709⟩,
    ⟨717, 3, 5, 709⟩,
    ⟨719, 3, 7, 709⟩,
    ⟨721, 3, 17, 701⟩,
    ⟨723, 3, 11, 709⟩,
    ⟨725, 3, 3, 719⟩,
    ⟨727, 3, 5, 719⟩,
    ⟨729, 3, 7, 719⟩,
    ⟨731, 3, 19, 709⟩,
    ⟨733, 3, 3, 727⟩,
    ⟨735, 3, 5, 727⟩,
    ⟨737, 3, 7, 727⟩,
    ⟨739, 3, 3, 733⟩,
    ⟨741, 3, 5, 733⟩,
    ⟨743, 3, 7, 733⟩]

theorem checked22 : checkOddRun 713 744 certificates22 = true := by
  norm_num [checkOddRun, checkCertificate, certificates22]

theorem length22 : certificates22.length = 16 := by decide

def certificates23 : List Certificate :=
  [⟨745, 3, 3, 739⟩,
    ⟨747, 3, 5, 739⟩,
    ⟨749, 3, 3, 743⟩,
    ⟨751, 3, 5, 743⟩,
    ⟨753, 3, 7, 743⟩,
    ⟨755, 3, 13, 739⟩,
    ⟨757, 3, 3, 751⟩,
    ⟨759, 3, 5, 751⟩,
    ⟨761, 3, 7, 751⟩,
    ⟨763, 3, 3, 757⟩,
    ⟨765, 3, 5, 757⟩,
    ⟨767, 3, 3, 761⟩,
    ⟨769, 3, 5, 761⟩,
    ⟨771, 3, 7, 761⟩,
    ⟨773, 3, 13, 757⟩,
    ⟨775, 3, 3, 769⟩]

theorem checked23 : checkOddRun 745 776 certificates23 = true := by
  norm_num [checkOddRun, checkCertificate, certificates23]

theorem length23 : certificates23.length = 16 := by decide

def certificates24 : List Certificate :=
  [⟨777, 3, 5, 769⟩,
    ⟨779, 3, 3, 773⟩,
    ⟨781, 3, 5, 773⟩,
    ⟨783, 3, 7, 773⟩,
    ⟨785, 3, 13, 769⟩,
    ⟨787, 3, 11, 773⟩,
    ⟨789, 3, 13, 773⟩,
    ⟨791, 3, 19, 769⟩,
    ⟨793, 3, 3, 787⟩,
    ⟨795, 3, 5, 787⟩,
    ⟨797, 3, 7, 787⟩,
    ⟨799, 3, 23, 773⟩,
    ⟨801, 3, 11, 787⟩,
    ⟨803, 3, 3, 797⟩,
    ⟨805, 3, 5, 797⟩,
    ⟨807, 3, 7, 797⟩]

theorem checked24 : checkOddRun 777 808 certificates24 = true := by
  norm_num [checkOddRun, checkCertificate, certificates24]

theorem length24 : certificates24.length = 16 := by decide

def certificates25 : List Certificate :=
  [⟨809, 3, 19, 787⟩,
    ⟨811, 3, 11, 797⟩,
    ⟨813, 3, 13, 797⟩,
    ⟨815, 3, 3, 809⟩,
    ⟨817, 3, 3, 811⟩,
    ⟨819, 3, 5, 811⟩,
    ⟨821, 3, 7, 811⟩,
    ⟨823, 3, 11, 809⟩,
    ⟨825, 3, 11, 811⟩,
    ⟨827, 3, 3, 821⟩,
    ⟨829, 3, 3, 823⟩,
    ⟨831, 3, 5, 823⟩,
    ⟨833, 3, 3, 827⟩,
    ⟨835, 3, 3, 829⟩,
    ⟨837, 3, 5, 829⟩,
    ⟨839, 3, 7, 829⟩]

theorem checked25 : checkOddRun 809 840 certificates25 = true := by
  norm_num [checkOddRun, checkCertificate, certificates25]

theorem length25 : certificates25.length = 16 := by decide

def certificates26 : List Certificate :=
  [⟨841, 3, 11, 827⟩,
    ⟨843, 3, 11, 829⟩,
    ⟨845, 3, 3, 839⟩,
    ⟨847, 3, 5, 839⟩,
    ⟨849, 3, 7, 839⟩,
    ⟨851, 3, 19, 829⟩,
    ⟨853, 3, 11, 839⟩,
    ⟨855, 3, 13, 839⟩,
    ⟨857, 3, 31, 823⟩,
    ⟨859, 3, 3, 853⟩,
    ⟨861, 3, 5, 853⟩,
    ⟨863, 3, 3, 857⟩,
    ⟨865, 3, 3, 859⟩,
    ⟨867, 3, 5, 859⟩,
    ⟨869, 3, 3, 863⟩,
    ⟨871, 3, 5, 863⟩]

theorem checked26 : checkOddRun 841 872 certificates26 = true := by
  norm_num [checkOddRun, checkCertificate, certificates26]

theorem length26 : certificates26.length = 16 := by decide

def certificates27 : List Certificate :=
  [⟨873, 3, 7, 863⟩,
    ⟨875, 3, 13, 859⟩,
    ⟨877, 3, 11, 863⟩,
    ⟨879, 3, 13, 863⟩,
    ⟨881, 3, 19, 859⟩,
    ⟨883, 3, 3, 877⟩,
    ⟨885, 3, 5, 877⟩,
    ⟨887, 3, 3, 881⟩,
    ⟨889, 3, 3, 883⟩,
    ⟨891, 3, 5, 883⟩,
    ⟨893, 3, 3, 887⟩,
    ⟨895, 3, 5, 887⟩,
    ⟨897, 3, 7, 887⟩,
    ⟨899, 3, 13, 883⟩,
    ⟨901, 3, 11, 887⟩,
    ⟨903, 3, 13, 887⟩]

theorem checked27 : checkOddRun 873 904 certificates27 = true := by
  norm_num [checkOddRun, checkCertificate, certificates27]

theorem length27 : certificates27.length = 16 := by decide

def certificates28 : List Certificate :=
  [⟨905, 3, 19, 883⟩,
    ⟨907, 3, 17, 887⟩,
    ⟨909, 3, 19, 887⟩,
    ⟨911, 3, 31, 877⟩,
    ⟨913, 3, 3, 907⟩,
    ⟨915, 3, 5, 907⟩,
    ⟨917, 3, 3, 911⟩,
    ⟨919, 3, 5, 911⟩,
    ⟨921, 3, 7, 911⟩,
    ⟨923, 3, 13, 907⟩,
    ⟨925, 3, 3, 919⟩,
    ⟨927, 3, 5, 919⟩,
    ⟨929, 3, 7, 919⟩,
    ⟨931, 3, 17, 911⟩,
    ⟨933, 3, 11, 919⟩,
    ⟨935, 3, 3, 929⟩]

theorem checked28 : checkOddRun 905 936 certificates28 = true := by
  norm_num [checkOddRun, checkCertificate, certificates28]

theorem length28 : certificates28.length = 16 := by decide

def certificates29 : List Certificate :=
  [⟨937, 3, 5, 929⟩,
    ⟨939, 3, 7, 929⟩,
    ⟨941, 3, 19, 919⟩,
    ⟨943, 3, 3, 937⟩,
    ⟨945, 3, 5, 937⟩,
    ⟨947, 3, 3, 941⟩,
    ⟨949, 3, 5, 941⟩,
    ⟨951, 3, 7, 941⟩,
    ⟨953, 3, 3, 947⟩,
    ⟨955, 3, 5, 947⟩,
    ⟨957, 3, 7, 947⟩,
    ⟨959, 3, 3, 953⟩,
    ⟨961, 3, 5, 953⟩,
    ⟨963, 3, 7, 953⟩,
    ⟨965, 3, 43, 919⟩,
    ⟨967, 3, 11, 953⟩]

theorem checked29 : checkOddRun 937 968 certificates29 = true := by
  norm_num [checkOddRun, checkCertificate, certificates29]

theorem length29 : certificates29.length = 16 := by decide

def certificates30 : List Certificate :=
  [⟨969, 3, 13, 953⟩,
    ⟨971, 3, 31, 937⟩,
    ⟨973, 3, 3, 967⟩,
    ⟨975, 3, 5, 967⟩,
    ⟨977, 3, 3, 971⟩,
    ⟨979, 3, 5, 971⟩,
    ⟨981, 3, 7, 971⟩,
    ⟨983, 3, 3, 977⟩,
    ⟨985, 3, 5, 977⟩,
    ⟨987, 3, 7, 977⟩,
    ⟨989, 3, 3, 983⟩,
    ⟨991, 3, 5, 983⟩,
    ⟨993, 3, 7, 983⟩,
    ⟨995, 3, 73, 919⟩,
    ⟨997, 3, 3, 991⟩,
    ⟨999, 3, 5, 991⟩]

theorem checked30 : checkOddRun 969 1000 certificates30 = true := by
  norm_num [checkOddRun, checkCertificate, certificates30]

theorem length30 : certificates30.length = 16 := by decide

def suffix30 : List Certificate := certificates30

theorem suffixLength30 : suffix30.length = 16 := length30

theorem suffixChecked30 : checkOddRun 969 1000 suffix30 = true :=
  checked30

def suffix29 : List Certificate := certificates29 ++ suffix30

theorem suffixLength29 : suffix29.length = 32 := by
  rw [suffix29, List.length_append, length29, suffixLength30]

theorem suffixChecked29 : checkOddRun 937 1000 suffix29 = true :=
  checkOddRun_append (mid := 969) (by decide) (by decide)
    checked29 suffixChecked30

def suffix28 : List Certificate := certificates28 ++ suffix29

theorem suffixLength28 : suffix28.length = 48 := by
  rw [suffix28, List.length_append, length28, suffixLength29]

theorem suffixChecked28 : checkOddRun 905 1000 suffix28 = true :=
  checkOddRun_append (mid := 937) (by decide) (by decide)
    checked28 suffixChecked29

def suffix27 : List Certificate := certificates27 ++ suffix28

theorem suffixLength27 : suffix27.length = 64 := by
  rw [suffix27, List.length_append, length27, suffixLength28]

theorem suffixChecked27 : checkOddRun 873 1000 suffix27 = true :=
  checkOddRun_append (mid := 905) (by decide) (by decide)
    checked27 suffixChecked28

def suffix26 : List Certificate := certificates26 ++ suffix27

theorem suffixLength26 : suffix26.length = 80 := by
  rw [suffix26, List.length_append, length26, suffixLength27]

theorem suffixChecked26 : checkOddRun 841 1000 suffix26 = true :=
  checkOddRun_append (mid := 873) (by decide) (by decide)
    checked26 suffixChecked27

def suffix25 : List Certificate := certificates25 ++ suffix26

theorem suffixLength25 : suffix25.length = 96 := by
  rw [suffix25, List.length_append, length25, suffixLength26]

theorem suffixChecked25 : checkOddRun 809 1000 suffix25 = true :=
  checkOddRun_append (mid := 841) (by decide) (by decide)
    checked25 suffixChecked26

def suffix24 : List Certificate := certificates24 ++ suffix25

theorem suffixLength24 : suffix24.length = 112 := by
  rw [suffix24, List.length_append, length24, suffixLength25]

theorem suffixChecked24 : checkOddRun 777 1000 suffix24 = true :=
  checkOddRun_append (mid := 809) (by decide) (by decide)
    checked24 suffixChecked25

def suffix23 : List Certificate := certificates23 ++ suffix24

theorem suffixLength23 : suffix23.length = 128 := by
  rw [suffix23, List.length_append, length23, suffixLength24]

theorem suffixChecked23 : checkOddRun 745 1000 suffix23 = true :=
  checkOddRun_append (mid := 777) (by decide) (by decide)
    checked23 suffixChecked24

def suffix22 : List Certificate := certificates22 ++ suffix23

theorem suffixLength22 : suffix22.length = 144 := by
  rw [suffix22, List.length_append, length22, suffixLength23]

theorem suffixChecked22 : checkOddRun 713 1000 suffix22 = true :=
  checkOddRun_append (mid := 745) (by decide) (by decide)
    checked22 suffixChecked23

def suffix21 : List Certificate := certificates21 ++ suffix22

theorem suffixLength21 : suffix21.length = 160 := by
  rw [suffix21, List.length_append, length21, suffixLength22]

theorem suffixChecked21 : checkOddRun 681 1000 suffix21 = true :=
  checkOddRun_append (mid := 713) (by decide) (by decide)
    checked21 suffixChecked22

def suffix20 : List Certificate := certificates20 ++ suffix21

theorem suffixLength20 : suffix20.length = 176 := by
  rw [suffix20, List.length_append, length20, suffixLength21]

theorem suffixChecked20 : checkOddRun 649 1000 suffix20 = true :=
  checkOddRun_append (mid := 681) (by decide) (by decide)
    checked20 suffixChecked21

def suffix19 : List Certificate := certificates19 ++ suffix20

theorem suffixLength19 : suffix19.length = 192 := by
  rw [suffix19, List.length_append, length19, suffixLength20]

theorem suffixChecked19 : checkOddRun 617 1000 suffix19 = true :=
  checkOddRun_append (mid := 649) (by decide) (by decide)
    checked19 suffixChecked20

def suffix18 : List Certificate := certificates18 ++ suffix19

theorem suffixLength18 : suffix18.length = 208 := by
  rw [suffix18, List.length_append, length18, suffixLength19]

theorem suffixChecked18 : checkOddRun 585 1000 suffix18 = true :=
  checkOddRun_append (mid := 617) (by decide) (by decide)
    checked18 suffixChecked19

def suffix17 : List Certificate := certificates17 ++ suffix18

theorem suffixLength17 : suffix17.length = 224 := by
  rw [suffix17, List.length_append, length17, suffixLength18]

theorem suffixChecked17 : checkOddRun 553 1000 suffix17 = true :=
  checkOddRun_append (mid := 585) (by decide) (by decide)
    checked17 suffixChecked18

def suffix16 : List Certificate := certificates16 ++ suffix17

theorem suffixLength16 : suffix16.length = 240 := by
  rw [suffix16, List.length_append, length16, suffixLength17]

theorem suffixChecked16 : checkOddRun 521 1000 suffix16 = true :=
  checkOddRun_append (mid := 553) (by decide) (by decide)
    checked16 suffixChecked17

def suffix15 : List Certificate := certificates15 ++ suffix16

theorem suffixLength15 : suffix15.length = 256 := by
  rw [suffix15, List.length_append, length15, suffixLength16]

theorem suffixChecked15 : checkOddRun 489 1000 suffix15 = true :=
  checkOddRun_append (mid := 521) (by decide) (by decide)
    checked15 suffixChecked16

def suffix14 : List Certificate := certificates14 ++ suffix15

theorem suffixLength14 : suffix14.length = 272 := by
  rw [suffix14, List.length_append, length14, suffixLength15]

theorem suffixChecked14 : checkOddRun 457 1000 suffix14 = true :=
  checkOddRun_append (mid := 489) (by decide) (by decide)
    checked14 suffixChecked15

def suffix13 : List Certificate := certificates13 ++ suffix14

theorem suffixLength13 : suffix13.length = 288 := by
  rw [suffix13, List.length_append, length13, suffixLength14]

theorem suffixChecked13 : checkOddRun 425 1000 suffix13 = true :=
  checkOddRun_append (mid := 457) (by decide) (by decide)
    checked13 suffixChecked14

def suffix12 : List Certificate := certificates12 ++ suffix13

theorem suffixLength12 : suffix12.length = 304 := by
  rw [suffix12, List.length_append, length12, suffixLength13]

theorem suffixChecked12 : checkOddRun 393 1000 suffix12 = true :=
  checkOddRun_append (mid := 425) (by decide) (by decide)
    checked12 suffixChecked13

def suffix11 : List Certificate := certificates11 ++ suffix12

theorem suffixLength11 : suffix11.length = 320 := by
  rw [suffix11, List.length_append, length11, suffixLength12]

theorem suffixChecked11 : checkOddRun 361 1000 suffix11 = true :=
  checkOddRun_append (mid := 393) (by decide) (by decide)
    checked11 suffixChecked12

def suffix10 : List Certificate := certificates10 ++ suffix11

theorem suffixLength10 : suffix10.length = 336 := by
  rw [suffix10, List.length_append, length10, suffixLength11]

theorem suffixChecked10 : checkOddRun 329 1000 suffix10 = true :=
  checkOddRun_append (mid := 361) (by decide) (by decide)
    checked10 suffixChecked11

def suffix09 : List Certificate := certificates09 ++ suffix10

theorem suffixLength09 : suffix09.length = 352 := by
  rw [suffix09, List.length_append, length09, suffixLength10]

theorem suffixChecked09 : checkOddRun 297 1000 suffix09 = true :=
  checkOddRun_append (mid := 329) (by decide) (by decide)
    checked09 suffixChecked10

def suffix08 : List Certificate := certificates08 ++ suffix09

theorem suffixLength08 : suffix08.length = 368 := by
  rw [suffix08, List.length_append, length08, suffixLength09]

theorem suffixChecked08 : checkOddRun 265 1000 suffix08 = true :=
  checkOddRun_append (mid := 297) (by decide) (by decide)
    checked08 suffixChecked09

def suffix07 : List Certificate := certificates07 ++ suffix08

theorem suffixLength07 : suffix07.length = 384 := by
  rw [suffix07, List.length_append, length07, suffixLength08]

theorem suffixChecked07 : checkOddRun 233 1000 suffix07 = true :=
  checkOddRun_append (mid := 265) (by decide) (by decide)
    checked07 suffixChecked08

def suffix06 : List Certificate := certificates06 ++ suffix07

theorem suffixLength06 : suffix06.length = 400 := by
  rw [suffix06, List.length_append, length06, suffixLength07]

theorem suffixChecked06 : checkOddRun 201 1000 suffix06 = true :=
  checkOddRun_append (mid := 233) (by decide) (by decide)
    checked06 suffixChecked07

def suffix05 : List Certificate := certificates05 ++ suffix06

theorem suffixLength05 : suffix05.length = 416 := by
  rw [suffix05, List.length_append, length05, suffixLength06]

theorem suffixChecked05 : checkOddRun 169 1000 suffix05 = true :=
  checkOddRun_append (mid := 201) (by decide) (by decide)
    checked05 suffixChecked06

def suffix04 : List Certificate := certificates04 ++ suffix05

theorem suffixLength04 : suffix04.length = 432 := by
  rw [suffix04, List.length_append, length04, suffixLength05]

theorem suffixChecked04 : checkOddRun 137 1000 suffix04 = true :=
  checkOddRun_append (mid := 169) (by decide) (by decide)
    checked04 suffixChecked05

def suffix03 : List Certificate := certificates03 ++ suffix04

theorem suffixLength03 : suffix03.length = 448 := by
  rw [suffix03, List.length_append, length03, suffixLength04]

theorem suffixChecked03 : checkOddRun 105 1000 suffix03 = true :=
  checkOddRun_append (mid := 137) (by decide) (by decide)
    checked03 suffixChecked04

def suffix02 : List Certificate := certificates02 ++ suffix03

theorem suffixLength02 : suffix02.length = 464 := by
  rw [suffix02, List.length_append, length02, suffixLength03]

theorem suffixChecked02 : checkOddRun 73 1000 suffix02 = true :=
  checkOddRun_append (mid := 105) (by decide) (by decide)
    checked02 suffixChecked03

def suffix01 : List Certificate := certificates01 ++ suffix02

theorem suffixLength01 : suffix01.length = 480 := by
  rw [suffix01, List.length_append, length01, suffixLength02]

theorem suffixChecked01 : checkOddRun 41 1000 suffix01 = true :=
  checkOddRun_append (mid := 73) (by decide) (by decide)
    checked01 suffixChecked02

def suffix00 : List Certificate := certificates00 ++ suffix01

theorem suffixLength00 : suffix00.length = 496 := by
  rw [suffix00, List.length_append, length00, suffixLength01]

theorem suffixChecked00 : checkOddRun 9 1000 suffix00 = true :=
  checkOddRun_append (mid := 41) (by decide) (by decide)
    checked00 suffixChecked01

def regressionCertificates : List Certificate := suffix00

theorem regression_length : regressionCertificates.length = 496 := suffixLength00

theorem regression_run_checked : checkOddRun 9 1000 regressionCertificates = true :=
  suffixChecked00

theorem regression_checked : checkInterval 9 1000 regressionCertificates = true :=
  checkInterval_of_checkOddRun (by decide) regression_run_checked

theorem threeOddPrimes_9_1000 (n : ℕ) (hlo : 9 ≤ n) (hhi : n ≤ 1000)
    (hodd : Odd n) : LiuWang.IsThreeOddPrimeSum n :=
  checkInterval_sound regression_checked n hlo hhi hodd

theorem regression_indices :
    regressionCertificates.map Certificate.n =
      (List.range 496).map (fun k => 9 + 2 * k) := by
  simpa only [regression_length] using checkOddRun_indices regression_run_checked

end LiuWang.Proof.FiniteTernaryClosure
