import LiuWang.Proof.SourceRoute.SecondArc.OriginalIntegrals

namespace LiuWang.Proof.SourceRoute.SecondArc

#print axioms heightKernel
#print axioms heightKernel_nonneg
#print axioms heightKernel_integrable
#print axioms integral_heightKernel
#print axioms heightKernel_indicator_integrable
#print axioms heightKernel_lower_indicator
#print axioms heightKernel_upper_indicator_integrable
#print axioms heightKernel_upper_indicator
#print axioms heightKernel_closed_indicator_integrable
#print axioms heightKernel_closed_indicator
#print axioms cumulativeWeight
#print axioms height_integrand_eq_sum
#print axioms height_integrand_integrable
#print axioms finite_height_abel
#print axioms cumulativeWeight_mono
#print axioms finite_height_abel_le
#print axioms count_eq_cumulative
#print axioms count_height_integrable
#print axioms familyCount_height_integrable
#print axioms character_height_abel
#print axioms family_height_abel
#print axioms normalized_complete_height_abel
#print axioms alphaKernel
#print axioms continuous_alphaKernel
#print axioms integral_alphaKernel
#print axioms alpha_indicator_integrable
#print axioms alpha_indicator_integral
#print axioms bandMass
#print axioms bandMass_alpha_integrand
#print axioms bandMass_alpha_integrable
#print axioms band_weight_alpha_identity
#print axioms band_weight_alpha_split
#print axioms middlePacket
#print axioms middlePacket_eq_complete
#print axioms norm_middlePacket_le_weighted
#print axioms norm_middlePacket_le_alpha_integrals
#print axioms integral_exp_affine
#print axioms integral_exp_density_cap
#print axioms integral_exp_density_cap_le
#print axioms integral_alpha_strip
#print axioms source_515_first_strip
#print axioms source_515_last_strip
#print axioms density_cap_exponent
#print axioms density_cap_integral_le
#print axioms sourceSeven_envelope
#print axioms sourceSeven_weight_envelope
#print axioms sourceSeven_integral_le_ordered
#print axioms sourceSeven_integral_le
#print axioms log_height_jacobian
#print axioms log_height_change
#print axioms normalized_log_height_change
#print axioms log_height_source_endpoints
#print axioms source_516_log_integral
#print axioms source_517_log_integral
#print axioms middleUpper
#print axioms log_large_le
#print axioms log_ten_pi_le_four
#print axioms log_window_lower
#print axioms middle_height_domain
#print axioms middle_log_domain
#print axioms source_53_packet
#print axioms source_54_height
#print axioms count_alpha_integrable
#print axioms density_rectangle_finite
#print axioms density_rectangle_integrable
#print axioms density_rectangle_swap
#print axioms density_alpha_outer_integrable
#print axioms alpha_height_reduction
#print axioms log_window_eq
#print axioms window_base_ge_one
#print axioms source_57_middle_packet
#print axioms source_59_inner
#print axioms source_log_endpoints
#print axioms source_516_kernel_identity
#print axioms source_517_kernel_identity

end LiuWang.Proof.SourceRoute.SecondArc
