import LiuWang.Proof.SourceRoute.ThirdArc.BoundaryChecks

namespace LiuWang.Proof.SourceRoute.ThirdArc

#print axioms lowHeight
#print axioms middleHeight
#print axioms lowKernel
#print axioms middleKernel
#print axioms highKernel
#print axioms bandMass
#print axioms sigma4
#print axioms sigma5
#print axioms sigma6
#print axioms lowHeight_pos
#print axioms middleHeight_pos
#print axioms near_condition
#print axioms lowKernel_nonneg
#print axioms three_kernel_bound
#print axioms family_three_bands
#print axioms zeroPacket_three_bands
#print axioms S_three_bands
#print axioms heightKernel
#print axioms heightKernel_integrable
#print axioms integral_heightKernel
#print axioms indicator_integrable
#print axioms integral_height_tail
#print axioms cumulative
#print axioms cumulative_integrand
#print axioms cumulative_integrable
#print axioms finite_height_partialSummation
#print axioms betaKernel
#print axioms betaKernel_continuous
#print axioms integral_betaKernel
#print axioms upperMass
#print axioms upperMass_integrand
#print axioms upperMass_integrable
#print axioms finite_beta_partialSummation
#print axioms zeroValues_height_filter
#print axioms count_eq_cumulative
#print axioms count_height_integrable
#print axioms band_cumulative_le_count
#print axioms character_height_partialSummation
#print axioms densityBand
#print axioms family_height_integrable
#print axioms family_height_partialSummation
#print axioms equation_5_29
#print axioms equation_5_39
#print axioms bandValues_beta_filter
#print axioms upperMass_eq_band
#print axioms character_beta_integrable
#print axioms densityBand_beta_integrable
#print axioms betaMoment
#print axioms character_beta_partialSummation
#print axioms betaMoment_partialSummation
#print axioms betaMoment_source_split
#print axioms original_height_order
#print axioms complete_band_eq_count_band
#print axioms middleKernel_eq_beta
#print axioms highKernel_eq_beta
#print axioms sigma5_eq_betaMoment
#print axioms sigma6_eq_betaMoment
#print axioms equation_5_28
#print axioms equation_5_38
#print axioms lowCoefficient
#print axioms lowCoefficient_integral
#print axioms lowCoefficient_antitone
#print axioms lowCoefficient_nonneg
#print axioms lowCoefficient_continuousOn
#print axioms low_integrand_integrable
#print axioms low_single_partialSummation
#print axioms finite_low_partialSummation
#print axioms low_character_partialSummation
#print axioms primeS
#print axioms lambda_sub_prime_identity
#print axioms norm_lambda_sub_prime_le_mass
#print axioms norm_lambda_sub_prime_le
#print axioms primeS_three_bands
#print axioms middle_eta_scale
#print axioms middle_error_le
#print axioms middle_error_paid
#print axioms primePower_error_paid
#print axioms primeS_M3_fixed
#print axioms S_M3_fixed
#print axioms primeS_M3_same_witness
#print axioms M3_same_witness
#print axioms real_zero_in_low_band
#print axioms real_zero_not_middle_band
#print axioms collapsed_height_interval
#print axioms beta_lower_endpoint

end LiuWang.Proof.SourceRoute.ThirdArc
