import LiuWang.Proof.EffectiveLValue.EvenHelpers.CyclotomicIntegral
import Mathlib.NumberTheory.Cyclotomic.Gal
import Mathlib.RingTheory.RootsOfUnity.Complex

/-!
# Galois action on the actual cyclotomic product

The ambient field is the subfield of `ℂ` generated by `stdAddChar 1`.
Its product coerces definitionally to the finite product used in the Abel
identity. The two possible conjugates are the product and its inverse.
-/

set_option autoImplicit false

noncomputable section

namespace LiuWang.Proof.EffectiveLValue

open Complex Finset

variable {r : ℕ} [NeZero r]

def characterCyclotomicAmbient (r : ℕ) [NeZero r] : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ {ZMod.stdAddChar (1 : ZMod r)}

theorem stdAddChar_one_isPrimitiveRoot :
    IsPrimitiveRoot (ZMod.stdAddChar (1 : ZMod r)) r := by
  have h := ZMod.stdAddChar_coe (N := r) (1 : ℤ)
  simp only [Int.cast_one, mul_one] at h
  rw [h]
  exact Complex.isPrimitiveRoot_exp r (NeZero.ne r)

instance characterCyclotomicAmbient_cyclotomic :
    IsCyclotomicExtension {r} ℚ (characterCyclotomicAmbient r) := by
  change IsCyclotomicExtension {r} ℚ
    (IntermediateField.adjoin ℚ {ZMod.stdAddChar (1 : ZMod r)}).toSubalgebra
  rw [IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
    ((stdAddChar_one_isPrimitiveRoot.isIntegral (NeZero.pos r)).tower_top
      (A := ℚ)).isAlgebraic]
  exact stdAddChar_one_isPrimitiveRoot.adjoin_isCyclotomicExtension ℚ

instance characterCyclotomicAmbient_finite :
    FiniteDimensional ℚ (characterCyclotomicAmbient r) :=
  IsCyclotomicExtension.finiteDimensional {r} ℚ _

instance characterCyclotomicAmbient_galois :
    IsGalois ℚ (characterCyclotomicAmbient r) :=
  IsCyclotomicExtension.isGalois {r} ℚ _

def characterCyclotomicRoot (a : ZMod r) : characterCyclotomicAmbient r :=
  ⟨ZMod.stdAddChar a, by
    have h := (characterCyclotomicAmbient r).pow_mem
      (IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)) a.val
    simpa only [zpow_natCast, stdAddChar_pow_val_mul, mul_one] using h⟩

theorem characterCyclotomicRoot_pow (a b : ZMod r) :
    characterCyclotomicRoot b ^ a.val = characterCyclotomicRoot (a * b) := by
  apply Subtype.ext
  exact stdAddChar_pow_val_mul a b

theorem characterCyclotomicRoot_primitive :
    IsPrimitiveRoot (characterCyclotomicRoot (1 : ZMod r)) r := by
  exact stdAddChar_one_isPrimitiveRoot.of_map_of_injective
    (f := (characterCyclotomicAmbient r).val) Subtype.val_injective

def characterCyclotomicAutIndex
    (σ : characterCyclotomicAmbient r ≃ₐ[ℚ] characterCyclotomicAmbient r) : (ZMod r)ˣ :=
  characterCyclotomicRoot_primitive.autToPow ℚ σ

theorem characterCyclotomicRoot_aut
    (σ : characterCyclotomicAmbient r ≃ₐ[ℚ] characterCyclotomicAmbient r) (a : ZMod r) :
    σ (characterCyclotomicRoot a) =
      characterCyclotomicRoot ((characterCyclotomicAutIndex σ : ZMod r) * a) := by
  have h := characterCyclotomicRoot_primitive.autToPow_spec ℚ σ
  change characterCyclotomicRoot (1 : ZMod r) ^
    (characterCyclotomicAutIndex σ : ZMod r).val = σ (characterCyclotomicRoot 1) at h
  rw [characterCyclotomicRoot_pow, mul_one] at h
  have ha := characterCyclotomicRoot_pow a (1 : ZMod r)
  rw [mul_one] at ha
  rw [← ha, map_pow, ← h, characterCyclotomicRoot_pow, mul_comm]

def characterCyclotomicProductInField (χ : Interfaces.Character r) :
    characterCyclotomicAmbient r :=
  ∏ a : ZMod r, (1 - characterCyclotomicRoot a) ^ realCharacterSign χ a

theorem characterCyclotomicProductInField_coe (χ : Interfaces.Character r) :
    (characterCyclotomicProductInField χ : ℂ) = characterCyclotomicProduct χ := by
  change (characterCyclotomicAmbient r).val (∏ a : ZMod r,
    (1 - characterCyclotomicRoot a) ^ realCharacterSign χ a) = _
  rw [map_prod]
  apply prod_congr rfl
  intro a _
  calc
    _ = ((characterCyclotomicAmbient r).val (1 - characterCyclotomicRoot a)) ^
        realCharacterSign χ a :=
      map_zpow₀ (characterCyclotomicAmbient r).val _ _
    _ = _ := rfl

omit [NeZero r] in
theorem realCharacterSign_mul (χ : Interfaces.Character r) (hreal : χ ^ 2 = 1)
    (a b : ZMod r) :
    realCharacterSign χ (a * b) = realCharacterSign χ a * realCharacterSign χ b := by
  apply Int.cast_injective (α := ℂ)
  simp only [Int.cast_mul, realCharacterSign_cast χ hreal, map_mul]

omit [NeZero r] in
theorem realCharacterSign_unit (χ : Interfaces.Character r) (hreal : χ ^ 2 = 1)
    (u : (ZMod r)ˣ) : realCharacterSign χ (u : ZMod r) = 1 ∨
      realCharacterSign χ (u : ZMod r) = -1 := by
  rcases MulChar.isQuadratic_iff_sq_eq_one.mpr hreal (u : ZMod r) with h | h | h
  · exact False.elim ((MulChar.apply_ne_zero_iff.mpr u.isUnit) h)
  · left; simp [realCharacterSign, h]
  · right; norm_num [realCharacterSign, h]

theorem characterCyclotomicProductInField_aut (χ : Interfaces.Character r)
    (hreal : χ ^ 2 = 1)
    (σ : characterCyclotomicAmbient r ≃ₐ[ℚ] characterCyclotomicAmbient r) :
    σ (characterCyclotomicProductInField χ) =
      characterCyclotomicProductInField χ ^
        realCharacterSign χ (characterCyclotomicAutIndex σ : ZMod r) := by
  let u := characterCyclotomicAutIndex σ
  have hs : realCharacterSign χ (u : ZMod r) * realCharacterSign χ (u : ZMod r) = 1 := by
    rcases realCharacterSign_unit χ hreal u with h | h <;> rw [h] <;> norm_num
  have he (a : ZMod r) :
      realCharacterSign χ a =
        realCharacterSign χ (↑u * a) * realCharacterSign χ (u : ZMod r) := by
    rw [realCharacterSign_mul χ hreal, mul_right_comm, hs, one_mul]
  change _ = characterCyclotomicProductInField χ ^ realCharacterSign χ (u : ZMod r)
  unfold characterCyclotomicProductInField
  simp only [map_prod, map_zpow₀, map_sub, map_one, characterCyclotomicRoot_aut]
  calc
    _ = ∏ a : ZMod r,
        ((1 - characterCyclotomicRoot (↑u * a)) ^ realCharacterSign χ (↑u * a)) ^
          realCharacterSign χ (u : ZMod r) := by
      apply prod_congr rfl
      intro a _
      rw [← zpow_mul, ← he]
    _ = _ := by
      rw [Finset.prod_zpow]
      have hp := Equiv.prod_comp u.mulLeft
        (fun a : ZMod r ↦ (1 - characterCyclotomicRoot a) ^ realCharacterSign χ a)
      simp only [Units.mulLeft_apply] at hp
      exact congrArg (fun z ↦ z ^ realCharacterSign χ (u : ZMod r)) hp

theorem characterCyclotomicProductInField_aut_cases (χ : Interfaces.Character r)
    (hreal : χ ^ 2 = 1)
    (σ : characterCyclotomicAmbient r ≃ₐ[ℚ] characterCyclotomicAmbient r) :
    σ (characterCyclotomicProductInField χ) = characterCyclotomicProductInField χ ∨
      σ (characterCyclotomicProductInField χ) = (characterCyclotomicProductInField χ)⁻¹ := by
  rw [characterCyclotomicProductInField_aut χ hreal]
  rcases realCharacterSign_unit χ hreal (characterCyclotomicAutIndex σ) with h | h <;>
    simp [h]

def characterGaussSumInField (χ : Interfaces.Character r) : characterCyclotomicAmbient r :=
  ∑ a : ZMod r, (realCharacterSign χ a : characterCyclotomicAmbient r) *
    characterCyclotomicRoot a

theorem characterGaussSumInField_coe (χ : Interfaces.Character r) (hreal : χ ^ 2 = 1) :
    (characterGaussSumInField χ : ℂ) = characterGaussSum χ := by
  simp [characterGaussSumInField, characterGaussSum, gaussSum, characterCyclotomicRoot,
    realCharacterSign_cast χ hreal]

theorem characterGaussSumInField_aut (χ : Interfaces.Character r) (hreal : χ ^ 2 = 1)
    (σ : characterCyclotomicAmbient r ≃ₐ[ℚ] characterCyclotomicAmbient r) :
    σ (characterGaussSumInField χ) =
      (realCharacterSign χ (characterCyclotomicAutIndex σ : ZMod r) :
        characterCyclotomicAmbient r) * characterGaussSumInField χ := by
  let u := characterCyclotomicAutIndex σ
  have hs : realCharacterSign χ (u : ZMod r) * realCharacterSign χ (u : ZMod r) = 1 := by
    rcases realCharacterSign_unit χ hreal u with h | h <;> rw [h] <;> norm_num
  have he (a : ZMod r) :
      realCharacterSign χ a =
        realCharacterSign χ (u : ZMod r) * realCharacterSign χ (↑u * a) := by
    rw [realCharacterSign_mul χ hreal, ← mul_assoc, hs, one_mul]
  change _ = (realCharacterSign χ (u : ZMod r) : characterCyclotomicAmbient r) * _
  unfold characterGaussSumInField
  simp only [map_sum, map_mul, map_intCast, characterCyclotomicRoot_aut]
  calc
    _ = ∑ a : ZMod r,
        (realCharacterSign χ (u : ZMod r) : characterCyclotomicAmbient r) *
          ((realCharacterSign χ (↑u * a) : characterCyclotomicAmbient r) *
            characterCyclotomicRoot (↑u * a)) := by
      apply sum_congr rfl
      intro a _
      rw [he, Int.cast_mul, mul_assoc]
    _ = _ := by
      rw [← mul_sum]
      have hp := Equiv.sum_comp u.mulLeft
        (fun a : ZMod r ↦ (realCharacterSign χ a : characterCyclotomicAmbient r) *
          characterCyclotomicRoot a)
      simp only [Units.mulLeft_apply] at hp
      exact congrArg
        (fun z ↦ (realCharacterSign χ (u : ZMod r) : characterCyclotomicAmbient r) * z) hp

end LiuWang.Proof.EffectiveLValue
