import LiuWang.Proof.SourceRoute.MajorOrdinary.Continuation.Boundary

namespace LiuWang.Proof.SourceRoute.MajorOrdinary.Continuation

#print axioms nu
#print axioms nuKernel
#print axioms exp_gamma_ge_one
#print axioms log_hundred_thousand_ge_ten
#print axioms log_ten_ge_two
#print axioms large_log_bounds
#print axioms nu_pos
#print axioms nu_continuousOn
#print axioms nu_monotoneOn
#print axioms nu_ratio_le_loglog_ratio
#print axioms nu_growth
#print axioms nuKernel_nonneg
#print axioms nuKernel_continuousOn
#print axioms nuKernel_antitoneOn
#print axioms sourceP_ge_ten_billion
#print axioms correctedHarmonic
#print axioms corrected_log_step
#print axioms correctedHarmonic_step
#print axioms correctedHarmonic_limit
#print axioms gamma_le_correctedHarmonic
#print axioms gamma_le_decimal
#print axioms exp_gamma_le_decimal
#print axioms log_ten_billion_bounds
#print axioms loglog_ten_billion_bounds
#print axioms nu_ten_billion_le
#print axioms ten_billion_power_ge
#print axioms nu_le_source_power
#print axioms exp_tail_anchor
#print axioms source_power_tail_endpoint
#print axioms nuKernel_intervalIntegrable
#print axioms sum_Icc_shift
#print axioms nuKernel_sum_le_integral
#print axioms nuKernel_sum_le_integral_real
#print axioms totient_term_le_nuKernel
#print axioms totient_tail_le_source_integral
#print axioms source_integral_split
#print axioms source419_comparison
#print axioms source422_comparison
#print axioms lowTailExponent
#print axioms lowTailExponent_lt_neg_one
#print axioms low_kernel_le_power
#print axioms low_power_integrable
#print axioms low_kernel_integrable
#print axioms low_power_integral
#print axioms low_power_integral_le
#print axioms low_kernel_integral_le
#print axioms low_finite_tail_le
#print axioms high_tail_primitive_hasDerivAt
#print axioms high_power_intervalIntegrable
#print axioms high_power_integral
#print axioms ten_billion_sixth_root
#print axioms high_finite_tail_le
#print axioms source419_tail
#print axioms source422_tail
#print axioms totientRatioPower
#print axioms squareSum_totientRatioPower
#print axioms totientWeight_shift
#print axioms quadratic_moment_expansion
#print axioms cubic_moment_expansion
#print axioms I13_expanded_moments
#print axioms I14_expanded_moments
#print axioms totientWeight_le_plain
#print axioms totientMoment_split_le
#print axioms source421_literal_initial_terms
#print axioms source422_literal_initial_terms
#print axioms I12_literal_initial_terms
#print axioms linearPrefactor_le
#print axioms high_tail_div_P_le
#print axioms source423_scalar
#print axioms source420_at_endpoint
#print axioms first_tail_rectangle
#print axioms empty_tail_at_split
#print axioms high_tail_at_split
#print axioms nonsquarefree_quadratic_weight
#print axioms nonsquarefree_cubic_weight_positive

end LiuWang.Proof.SourceRoute.MajorOrdinary.Continuation
