import LiuWang.Proof.SourceRoute.LowSum.KOneCounts

set_option autoImplicit false

namespace LiuWang.Proof.SourceRoute.LowSum

#print axioms coefficient
#print axioms coefficientSlope
#print axioms kernel
#print axioms coefficient_hasDerivAt
#print axioms coefficientSlope_nonpos
#print axioms coefficient_antitone
#print axioms coefficient_nonneg
#print axioms continuousOn_kernel
#print axioms kernel_integrable
#print axioms kernel_nonneg
#print axioms weight_hasDerivAt
#print axioms weight_le_initial_add_integral
#print axioms integral_power_kernel
#print axioms integral_kernel_le_endpoint_difference
#print axioms countingFunction
#print axioms counting_integrand_eq
#print axioms indicator_kernel_integrable
#print axioms character_integrand_integrable
#print axioms counting_integrand_integrable
#print axioms counting_integral_eq
#print axioms finite_partial_summation
#print axioms finite_partial_summation_split
#print axioms countingFunction_full
#print axioms original_partial_summation
#print axioms original_low_partial_summation
#print axioms retained_partial_summation
#print axioms log_window_bounds
#print axioms coefficient_half_upper
#print axioms coefficient_098_bounds
#print axioms original_bulk_curly_bound
#print axioms original_log_seed
#print axioms decay_with_original_log_seed
#print axioms exp_neg_original_bulk_seed
#print axioms exp_neg_62
#print axioms exp_neg_fiftieth_decay
#print axioms original_bulk_integral_numeric
#print axioms integral_density_le
#print axioms countingFunction_le_full
#print axioms original_count_budget
#print axioms subset_bulk_integral_paid
#print axioms subset_original_reduction
#print axioms original_low_reduction
#print axioms retained_original_reduction
#print axioms paper_primed_original_reduction
#print axioms seedRatio
#print axioms original_log_seed_lower
#print axioms original_log_scale_lower
#print axioms exponential_difference_integral
#print axioms original_difference_decay
#print axioms cap_order
#print axioms cap_ge_098
#print axioms cap_power_eq
#print axioms segment_integral_le_of_coefficient
#print axioms original_segment_integral_le
#print axioms seedExp
#print axioms seed_enclosure
#print axioms seed_0478
#print axioms seed_0475
#print axioms seed_047
#print axioms seed_046
#print axioms seed_045
#print axioms seed_042
#print axioms seed_039
#print axioms seed_036
#print axioms seed_033
#print axioms seed_032
#print axioms segment_paid
#print axioms original_211
#print axioms original_212a
#print axioms original_212b
#print axioms original_212c
#print axioms original_212d
#print axioms original_212e
#print axioms original_212f
#print axioms original_212g
#print axioms original_212h
#print axioms breakpoint
#print axioms rowCount
#print axioms rowBudget
#print axioms row_parameters
#print axioms original_row_payment
#print axioms countingFunction_antitone
#print axioms countingFunction_nonneg
#print axioms actual_row_payment
#print axioms actual_rows_payment
#print axioms original_first_eight
#print axioms original_first_nine
#print axioms counting_integral_zero_tail
#print axioms original_213_from_counts
#print axioms exceptional_original_from_counts
#print axioms coefficient_le_of_rational_test
#print axioms cap_le_one
#print axioms coefficient_cap_032
#print axioms seed_c1
#print axioms original_215
#print axioms countingFunction_zero_above
#print axioms counting_integral_zero_above_cap
#print axioms original_two_zero_tail
#print axioms two_zero_original_from_counts
#print axioms paperCap
#print axioms coefficient_cap_small
#print axioms seed_012
#print axioms seed_015
#print axioms seed_02067
#print axioms seed_026213
#print axioms seed_02743
#print axioms small_segment_paid
#print axioms original_K1_middle
#print axioms original_K1_last
#print axioms ratio_fifth_le_first
#print axioms exp_neg_1332
#print axioms paper_endpoint_decay
#print axioms integral_constant_le_of_coefficient
#print axioms original_K1_small_expression
#print axioms original_K1_small
#print axioms counting_integral_le_open
#print axioms counting_integral_two_pieces
#print axioms original_K1_small_from_counts
#print axioms original_K1_middle_from_counts
#print axioms original_K1_last_from_counts

end LiuWang.Proof.SourceRoute.LowSum
