import LiuWang.Proof.VaughanRecovery.Consumer

/-! 完整公开声明清单；编译类型和递归公理由证据导出器另存。 -/

#print axioms LiuWang.Proof.VaughanRecovery.tailRatio
#print axioms LiuWang.Proof.VaughanRecovery.middleRatio
#print axioms LiuWang.Proof.VaughanRecovery.mother
#print axioms LiuWang.Proof.VaughanRecovery.variable_pair_le
#print axioms LiuWang.Proof.VaughanRecovery.termB_normalized
#print axioms LiuWang.Proof.VaughanRecovery.tail_normalized
#print axioms LiuWang.Proof.VaughanRecovery.mother_eq
#print axioms LiuWang.Proof.VaughanRecovery.three_terms_le_mother
#print axioms LiuWang.Proof.VaughanRecovery.continuous_three_terms_le_mother
#print axioms LiuWang.Proof.VaughanRecovery.continuous_three_terms_le_uniform
#print axioms LiuWang.Proof.VaughanRecovery.tailRatio_le
#print axioms LiuWang.Proof.VaughanRecovery.middleRatio_le
#print axioms LiuWang.Proof.VaughanRecovery.mother_le_uniform
#print axioms LiuWang.Proof.VaughanRecovery.M4_exists_strong
#print axioms LiuWang.Proof.VaughanRecovery.M4_approximation
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_mother
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_194
#print axioms LiuWang.Proof.VaughanRecovery.M4_closed_window_mother
#print axioms LiuWang.Proof.VaughanRecovery.M4_closed_window_194
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_294
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_300
#print axioms LiuWang.Proof.VaughanRecovery.primeBudget
#print axioms LiuWang.Proof.VaughanRecovery.scalar_budget_291
#print axioms LiuWang.Proof.VaughanRecovery.W1_add_high_le_primeBudget
#print axioms LiuWang.Proof.VaughanRecovery.primeBudget_le_291
#print axioms LiuWang.Proof.VaughanRecovery.actual_moment_le_primeBudget
#print axioms LiuWang.Proof.VaughanRecovery.actual_moment_le_291
#print axioms LiuWang.Proof.VaughanRecovery.moebiusMass
#print axioms LiuWang.Proof.VaughanRecovery.actualEnergy
#print axioms LiuWang.Proof.VaughanRecovery.energySum
#print axioms LiuWang.Proof.VaughanRecovery.recoveredKappa
#print axioms LiuWang.Proof.VaughanRecovery.moebiusMass_nonneg
#print axioms LiuWang.Proof.VaughanRecovery.moebiusMass_le_linear
#print axioms LiuWang.Proof.VaughanRecovery.block_sq_le_actualEnergy
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_energySum
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_actualEnergy
#print axioms LiuWang.Proof.VaughanRecovery.actualEnergy_le_moment_budget
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_W123
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_primeEnergy
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_linear_primeEnergy
#print axioms LiuWang.Proof.VaughanRecovery.block_sq_le_291
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_recoveredKappa
#print axioms LiuWang.Proof.VaughanRecovery.recoveredKappa_le
#print axioms LiuWang.Proof.VaughanRecovery.geometricRows
#print axioms LiuWang.Proof.VaughanRecovery.recoveredDyadicBudget
#print axioms LiuWang.Proof.VaughanRecovery.dyadicCount_le_three_tenths
#print axioms LiuWang.Proof.VaughanRecovery.sum_sqrt_rows_le_geometric
#print axioms LiuWang.Proof.VaughanRecovery.geometricRows_le
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_recoveredDyadicBudget
#print axioms LiuWang.Proof.VaughanRecovery.recoveredDyadicBudget_le_geometric
#print axioms LiuWang.Proof.VaughanRecovery.recoveredDyadicBudget_le_three_terms
#print axioms LiuWang.Proof.VaughanRecovery.typeIMajorant
#print axioms LiuWang.Proof.VaughanRecovery.sourceS_le_typeI_add
#print axioms LiuWang.Proof.VaughanRecovery.sourceS4_le_repaid
#print axioms LiuWang.Proof.VaughanRecovery.sourceS_le_repaid
#print axioms LiuWang.Proof.VaughanRecovery.M4_exists_repaid
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_repaid_mother
#print axioms LiuWang.Proof.VaughanRecovery.M4_le_1743
#print axioms LiuWang.Proof.VaughanRecovery.M4_closed_window_repaid_mother
#print axioms LiuWang.Proof.VaughanRecovery.M4_closed_window_1743
#print axioms LiuWang.Proof.VaughanRecovery.M4_closed_window_repaid_explicit
