

import MathlibNt.AnalyticNumberTheory.Vaughan.VaughanTypeIIPrimitiveBilinear
import MathlibNt.AnalyticNumberTheory.LargeSieve.PrefixMaximal

/-!
 # Actual tensor energy and rectangle aggregation for Vaughan Type II

This module bounds the coefficient obtained after collecting `t=e*m` by
Cauchy on the *actual fibre*.  The subsequent sum remains a sum in `(d,t)`;
it is never repackaged pointwise in `n=d*e*m`.
-/

namespace AnalyticNumberTheory.LargeSieve

open Classical Finset
open scoped BigOperators ArithmeticFunction

noncomputable section

/-- The actual `e`-fibre above `t`, including the physical cutoff on `m`. -/
def vaughanTensorFiber (y d : ℕ) (ES : Finset ℕ) (t : ℤ) : Finset ℕ :=
  ES.filter fun e => ∃ m ∈ Finset.Icc 1 (y / (d * e)), ((e * m : ℕ) : ℤ) = t

/-- Number of representations in the actual `t=e*m` fibre. -/
def vaughanTensorFiberMultiplicity (y d : ℕ) (ES : Finset ℕ) (t : ℤ) : ℕ :=
  (vaughanTensorFiber y d ES t).card

/-- The `Λ` square-energy on one actual fibre. -/
def vaughanTensorFiberMangoldtEnergy
    (y d : ℕ) (ES : Finset ℕ) (t : ℤ) : ℝ :=
  ∑ e ∈ vaughanTensorFiber y d ES t, ‖vaughanMangoldtCoeff e‖ ^ 2

/-- The external coefficient energy with precisely the multiplicity and
`Λ`-energy generated by fibre Cauchy.  Keeping this as a `(d,t)` sum is the
key distinction from a pointwise estimate after `n=d*e*m`. -/
def vaughanActualTensorCoeffEnergy
    (b : ℕ → ℂ) (y : ℕ) (DS ES : Finset ℕ) : ℝ :=
  ∑ d ∈ DS, ∑ t ∈ Finset.Icc (1 : ℤ) y,
    (vaughanTensorFiberMultiplicity y d ES t : ℝ) *
      vaughanTensorFiberMangoldtEnergy y d ES t * ‖b (d * t.toNat)‖ ^ 2

private theorem tensor_inner_sum_eq_indicator
    (z : ℂ) (y d e : ℕ) (t : ℤ) (he : 0 < e) :
    (∑ m ∈ Finset.Icc 1 (y / (d * e)),
      if ((e * m : ℕ) : ℤ) = t then z else 0) =
      if ∃ m ∈ Finset.Icc 1 (y / (d * e)), ((e * m : ℕ) : ℤ) = t then z else 0 := by
  by_cases h : ∃ m ∈ Finset.Icc 1 (y / (d * e)), ((e * m : ℕ) : ℤ) = t
  · obtain ⟨m, hm, hmt⟩ := h
    rw [if_pos ⟨m, hm, hmt⟩]
    rw [Finset.sum_eq_single m]
    · simp [hmt]
    · intro m' hm' hne
      rw [if_neg]
      intro hm't
      apply hne
      apply Nat.eq_of_mul_eq_mul_left he
      exact_mod_cast hm't.trans hmt.symm
    · intro hmnot
      exact False.elim (hmnot hm)
  · rw [if_neg h]
    apply Finset.sum_eq_zero
    intro m hm
    rw [if_neg]
    exact fun hmt => h ⟨m, hm, hmt⟩

/-- Exact fibre form of the actual Vaughan tensor coefficient. -/
theorem vaughanBilinearTensorCoeff_eq_fiber
    (b : ℕ → ℂ) (y d : ℕ) (ES : Finset ℕ) (t : ℤ)
    (hES : ∀ e ∈ ES, 0 < e) :
    vaughanBilinearTensorCoeff vaughanMangoldtCoeff b y d ES t =
      ∑ e ∈ vaughanTensorFiber y d ES t,
        vaughanMangoldtCoeff e * b (d * t.toNat) := by
  unfold vaughanBilinearTensorCoeff vaughanTensorFiber
  rw [Finset.sum_filter]
  apply Finset.sum_congr rfl
  intro e he
  rw [tensor_inner_sum_eq_indicator
    (vaughanMangoldtCoeff e * b (d * t.toNat)) y d e t (hES e he)]

/-- Cardinality-form Cauchy for the complex sums on fibres and rectangles. -/
private theorem norm_sum_sq_le_card_mul_sum_norm_sq {α : Type*}
    (s : Finset α) (f : α → ℂ) :
    ‖∑ a ∈ s, f a‖ ^ 2 ≤ (s.card : ℝ) * ∑ a ∈ s, ‖f a‖ ^ 2 := by
  classical
  exact norm_finset_sum_sq_le_card_mul_sum_norm_sq s f

/-- Cauchy on the actual divisor fibre.  Its two factors are the literal
fibre multiplicity and the literal `Λ` square-energy. -/
theorem vaughanBilinearTensorCoeff_norm_sq_le_fiber
    (b : ℕ → ℂ) (y d : ℕ) (ES : Finset ℕ) (t : ℤ)
    (hES : ∀ e ∈ ES, 0 < e) :
    ‖vaughanBilinearTensorCoeff vaughanMangoldtCoeff b y d ES t‖ ^ 2 ≤
      (vaughanTensorFiberMultiplicity y d ES t : ℝ) *
        vaughanTensorFiberMangoldtEnergy y d ES t *
          ‖b (d * t.toNat)‖ ^ 2 := by
  rw [vaughanBilinearTensorCoeff_eq_fiber b y d ES t hES]
  rw [← Finset.sum_mul, norm_mul, mul_pow]
  simpa [vaughanTensorFiberMultiplicity, vaughanTensorFiberMangoldtEnergy,
    mul_assoc] using
    mul_le_mul_of_nonneg_right
      (norm_sum_sq_le_card_mul_sum_norm_sq
        (vaughanTensorFiber y d ES t) vaughanMangoldtCoeff) (sq_nonneg ‖b (d * t.toNat)‖)

/-- The actual tensor energy is compressed without leaving the full `(d,t)`
sum.  No pointwise `D²E²` coefficient estimate occurs. -/
theorem vaughanBilinearTensorEnergy_le_actual
    (b : ℕ → ℂ) (y : ℕ) (DS ES : Finset ℕ)
    (hES : ∀ e ∈ ES, 0 < e) :
    vaughanBilinearTensorEnergy vaughanMangoldtCoeff b y DS ES ≤
      vaughanActualTensorCoeffEnergy b y DS ES := by
  unfold vaughanBilinearTensorEnergy vaughanActualTensorCoeffEnergy
  exact Finset.sum_le_sum fun d _ => Finset.sum_le_sum fun t _ =>
    vaughanBilinearTensorCoeff_norm_sq_le_fiber b y d ES t hES

lemma vaughanTensorFiberMangoldtEnergy_nonneg
    (y d : ℕ) (ES : Finset ℕ) (t : ℤ) :
    0 ≤ vaughanTensorFiberMangoldtEnergy y d ES t := by
  unfold vaughanTensorFiberMangoldtEnergy
  positivity

/-- A scalar consumer of the exact `(d,t)` ledger.  `Δ` is a divisor-fibre
multiplicity cap, `LΛ` a fibrewise Mangoldt-energy cap, and `B` the *summed*
external coefficient energy. -/
theorem vaughanBilinearTensorEnergy_le_of_fiber_caps
    (b : ℕ → ℂ) (y : ℕ) (DS ES : Finset ℕ) (Δ LΛ B : ℝ)
    (hES : ∀ e ∈ ES, 0 < e)
    (hΔ : ∀ d ∈ DS, ∀ t ∈ Finset.Icc (1 : ℤ) y,
      (vaughanTensorFiberMultiplicity y d ES t : ℝ) ≤ Δ)
    (hΛ : ∀ d ∈ DS, ∀ t ∈ Finset.Icc (1 : ℤ) y,
      vaughanTensorFiberMangoldtEnergy y d ES t ≤ LΛ)
    (hB : (∑ d ∈ DS, ∑ t ∈ Finset.Icc (1 : ℤ) y,
      ‖b (d * t.toNat)‖ ^ 2) ≤ B)
    (hΔ0 : 0 ≤ Δ) (hΛ0 : 0 ≤ LΛ) :
    vaughanBilinearTensorEnergy vaughanMangoldtCoeff b y DS ES ≤ Δ * LΛ * B := by
  refine (vaughanBilinearTensorEnergy_le_actual b y DS ES hES).trans ?_
  unfold vaughanActualTensorCoeffEnergy
  calc
    (∑ d ∈ DS, ∑ t ∈ Finset.Icc (1 : ℤ) y,
      (vaughanTensorFiberMultiplicity y d ES t : ℝ) *
        vaughanTensorFiberMangoldtEnergy y d ES t * ‖b (d * t.toNat)‖ ^ 2) ≤
      ∑ d ∈ DS, ∑ t ∈ Finset.Icc (1 : ℤ) y,
        Δ * LΛ * ‖b (d * t.toNat)‖ ^ 2 := by
          apply Finset.sum_le_sum
          intro d hd
          apply Finset.sum_le_sum
          intro t ht
          have hE0 := vaughanTensorFiberMangoldtEnergy_nonneg y d ES t
          have hb0 : 0 ≤ ‖b (d * t.toNat)‖ ^ 2 := sq_nonneg _
          exact mul_le_mul_of_nonneg_right
            (mul_le_mul (hΔ d hd t ht) (hΛ d hd t ht) hE0 hΔ0) hb0
    _ = Δ * LΛ * (∑ d ∈ DS, ∑ t ∈ Finset.Icc (1 : ℤ) y,
        ‖b (d * t.toNat)‖ ^ 2) := by
      simp_rw [Finset.mul_sum]
    _ ≤ Δ * LΛ * B := mul_le_mul_of_nonneg_left hB (mul_nonneg hΔ0 hΛ0)

/-- Möbius has unit pointwise square budget, hence its energy is at most the
literal outer-block cardinality. -/
theorem vaughanMoebiusCoeffEnergy_le_card (DS : Finset ℕ) :
    vaughanBilinearCoeffEnergy vaughanMoebiusCoeff DS ≤ (DS.card : ℝ) := by
  unfold vaughanBilinearCoeffEnergy vaughanMoebiusCoeff
  calc
    (∑ d ∈ DS, ‖((ArithmeticFunction.moebius d : ℤ) : ℂ)‖ ^ 2) ≤
        ∑ _d ∈ DS, (1 : ℝ) := by
      apply Finset.sum_le_sum
      intro d hd
      rcases ArithmeticFunction.moebius_eq_or d with h | h | h <;> simp [h]
    _ = (DS.card : ℝ) := by simp

/-- Actual canonical-block primitive bound after inserting the fibre and
external-coefficient energies. -/
theorem weighted_primitive_vaughanCanonicalBilinear_actual
    (b : ℕ → ℂ) (y N u v k l Q : ℕ) (Δ LΛ B : ℝ) (hQ : 0 < Q)
    (hΔ : ∀ d ∈ vaughanCanonicalDyadicBlock N u k,
      ∀ t ∈ Finset.Icc (1 : ℤ) y,
      (vaughanTensorFiberMultiplicity y d
        (vaughanCanonicalDyadicBlock N v l) t : ℝ) ≤ Δ)
    (hΛ : ∀ d ∈ vaughanCanonicalDyadicBlock N u k,
      ∀ t ∈ Finset.Icc (1 : ℤ) y,
      vaughanTensorFiberMangoldtEnergy y d
        (vaughanCanonicalDyadicBlock N v l) t ≤ LΛ)
    (hB : (∑ d ∈ vaughanCanonicalDyadicBlock N u k,
      ∑ t ∈ Finset.Icc (1 : ℤ) y, ‖b (d * t.toNat)‖ ^ 2) ≤ B)
    (hΔ0 : 0 ≤ Δ) (hΛ0 : 0 ≤ LΛ) :
    (∑ q ∈ Finset.Icc 1 Q, ((q : ℝ) / (q.totient : ℝ)) *
      ∑ χ : PrimitiveCharacter q,
        ‖vaughanTypeIICanonicalBilinearBlock b y N u v k l q χ‖ ^ 2) ≤
      (vaughanCanonicalDyadicBlock N u k).card *
        vaughanBilinearLargeSieveConstant y Q * (Δ * LΛ * B) := by
  refine (weighted_primitive_vaughanCanonicalBilinear b y N u v k l Q hQ).trans ?_
  have hμ := vaughanMoebiusCoeffEnergy_le_card
    (vaughanCanonicalDyadicBlock N u k)
  have hT := vaughanBilinearTensorEnergy_le_of_fiber_caps b y
    (vaughanCanonicalDyadicBlock N u k) (vaughanCanonicalDyadicBlock N v l)
    Δ LΛ B (fun e he => (mem_vaughanCanonicalDyadicBlock.mp he).1)
    hΔ hΛ hB hΔ0 hΛ0
  have hC0 : 0 ≤ vaughanBilinearLargeSieveConstant y Q := by
    unfold vaughanBilinearLargeSieveConstant largeSieveBound
    positivity
  have hT0 : 0 ≤ vaughanBilinearTensorEnergy vaughanMangoldtCoeff b y
      (vaughanCanonicalDyadicBlock N u k)
      (vaughanCanonicalDyadicBlock N v l) := by
    unfold vaughanBilinearTensorEnergy
    positivity
  exact mul_le_mul (mul_le_mul_of_nonneg_right hμ hC0) hT hT0
    (mul_nonneg (by positivity) hC0)

/-- Rectangle-count Cauchy, in the exact form used to reconstruct the full
Type-II prefix. -/
theorem vaughanTypeIIFullPrefix_norm_sq_le_rectangles
    (b : ℕ → ℂ) (y N u v q : ℕ) (χ : PrimitiveCharacter q) (hyN : y ≤ N) :
    ‖vaughanTypeIIFullPrefix b y u v q χ‖ ^ 2 ≤
      ((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2 *
        ∑ kl ∈ vaughanCanonicalDyadicRectangles N u v,
          ‖vaughanTypeIICanonicalBilinearBlock b y N u v
            kl.1 kl.2 q χ‖ ^ 2 := by
  rw [(vaughanTypeIIFullLedger b y N u v q χ hyN).1]
  let R := vaughanCanonicalDyadicRectangles N u v
  calc
    _ ≤ (R.card : ℝ) * ∑ kl ∈ R,
        ‖vaughanTypeIICanonicalBilinearBlock b y N u v kl.1 kl.2 q χ‖ ^ 2 :=
      norm_sum_sq_le_card_mul_sum_norm_sq R
        (fun kl => vaughanTypeIICanonicalBilinearBlock b y N u v kl.1 kl.2 q χ)
    _ ≤ (((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2) * ∑ kl ∈ R,
        ‖vaughanTypeIICanonicalBilinearBlock b y N u v kl.1 kl.2 q χ‖ ^ 2 := by
          apply mul_le_mul_of_nonneg_right
          · exact_mod_cast card_vaughanCanonicalDyadicRectangles_le N u v
          · positivity

/-- Full weighted primitive maximal ledger.  Rectangle Cauchy costs exactly
`(log₂ N+1)²`; the right side is the sum of the already proved canonical-block
primitive energies, so no second pointwise coefficient loss is introduced. -/
theorem weighted_primitive_vaughanTypeIIFullPrefix
    (b : ℕ → ℂ) (y N u v Q : ℕ) (hQ : 0 < Q) (hyN : y ≤ N) :
    (∑ q ∈ Finset.Icc 1 Q, ((q : ℝ) / (q.totient : ℝ)) *
      ∑ χ : PrimitiveCharacter q,
        ‖vaughanTypeIIFullPrefix b y u v q χ‖ ^ 2) ≤
      (((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2) *
        ∑ kl ∈ vaughanCanonicalDyadicRectangles N u v,
          (vaughanBilinearCoeffEnergy vaughanMoebiusCoeff
              (vaughanCanonicalDyadicBlock N u kl.1) *
            vaughanBilinearLargeSieveConstant y Q *
            vaughanBilinearTensorEnergy vaughanMangoldtCoeff b y
              (vaughanCanonicalDyadicBlock N u kl.1)
              (vaughanCanonicalDyadicBlock N v kl.2)) := by
  calc
    _ ≤ ∑ q ∈ Finset.Icc 1 Q, ((q : ℝ) / (q.totient : ℝ)) *
        ∑ χ : PrimitiveCharacter q,
          ((((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2) *
            ∑ kl ∈ vaughanCanonicalDyadicRectangles N u v,
              ‖vaughanTypeIICanonicalBilinearBlock b y N u v
                kl.1 kl.2 q χ‖ ^ 2) := by
      gcongr with q hq χ hχ
      exact vaughanTypeIIFullPrefix_norm_sq_le_rectangles b y N u v q χ hyN
    _ = (((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2) *
        ∑ kl ∈ vaughanCanonicalDyadicRectangles N u v,
          (∑ q ∈ Finset.Icc 1 Q, ((q : ℝ) / (q.totient : ℝ)) *
            ∑ χ : PrimitiveCharacter q,
              ‖vaughanTypeIICanonicalBilinearBlock b y N u v
                kl.1 kl.2 q χ‖ ^ 2) := by
      simp_rw [Finset.mul_sum]
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro kl hkl
      rw [Finset.sum_comm]
      ring
    _ ≤ (((Nat.log 2 N + 1 : ℕ) : ℝ) ^ 2) *
        ∑ kl ∈ vaughanCanonicalDyadicRectangles N u v,
          (vaughanBilinearCoeffEnergy vaughanMoebiusCoeff
              (vaughanCanonicalDyadicBlock N u kl.1) *
            vaughanBilinearLargeSieveConstant y Q *
            vaughanBilinearTensorEnergy vaughanMangoldtCoeff b y
              (vaughanCanonicalDyadicBlock N u kl.1)
              (vaughanCanonicalDyadicBlock N v kl.2)) := by
      gcongr with kl hkl
      exact weighted_primitive_vaughanCanonicalBilinear b y N u v
        kl.1 kl.2 Q hQ

end

end AnalyticNumberTheory.LargeSieve
