import LiuWang.Proof.Campaign20260915.ZetaValidation.OriginalHeightRemainder
import LiuWang.Proof.Campaign20260915.ZetaValidation.ActualMultiplicity
import LiuWang.Proof.Campaign20260915.ZetaValidation.StirlingRational
import LiuWang.Proof.Campaign20260915.ZetaValidation.NonzeroEvaluationCheck

namespace LiuWang.Proof.Campaign20260915.ZetaValidation

#check zeta_sub_eulerMaclaurinApprox
#check original_height_order64_remainder
#check original_height_critical_order64_remainder
#check gammaStirlingPhase_error
#check criticalGammaStirlingArgument_error
#check originalHeightGammaArgumentCenter_error
#check mem_zetaClosedValues
#check zetaClosedCount_one
#check zetaClosedCount_sixteen_lower
#check zetaClosedCount_sixteen_coarse_upper

#print axioms bernoulli_tail_step
#print axioms zeta_sub_eulerMaclaurinApprox
#print axioms abs_normalizedBernoulli_uniform
#print axioms eulerMaclaurin_geometric_error
#print axioms original_height_order64_remainder
#print axioms original_height_critical_order64_remainder
#print axioms original_height_normalized_order64_remainder
#print axioms gammaTrapezoidError_bound
#print axioms logGammaSeq_phase_identity
#print axioms gammaPhaseBoundary_tendsto_zero
#print axioms gammaStirlingPhase_error
#print axioms criticalGammaStirlingArgument_error
#print axioms criticalGammaPhase_stirling_error
#print axioms dyadicLog_error
#print axioms criticalGammaStirlingArgument_elementary
#print axioms originalHeightGammaArgumentCenter_error
#print axioms originalHeightGammaPhase_rational_argument_error
#print axioms zeta_order_positive_of_mem
#print axioms zetaClosedValues_card_le_count
#print axioms zetaClosedCount_one
#print axioms zeta_ne_zero_closed_height_one
#print axioms zetaClosedCount_sixteen_lower
#print axioms zetaClosedCount_sixteen_coarse_upper
#print axioms exists_nontrivial_zero_below_sixteen

end LiuWang.Proof.Campaign20260915.ZetaValidation
